/**
 * @fileoverview gRPC-Web generated client stub for event
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: event/event.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.event = require('./event_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.event.EventClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.event.EventPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.event.ListEventsRequest,
 *   !proto.event.ListEventsResponse>}
 */
const methodDescriptor_Event_ListEvents = new grpc.web.MethodDescriptor(
  '/event.Event/ListEvents',
  grpc.web.MethodType.UNARY,
  proto.event.ListEventsRequest,
  proto.event.ListEventsResponse,
  /**
   * @param {!proto.event.ListEventsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.event.ListEventsResponse.deserializeBinary
);


/**
 * @param {!proto.event.ListEventsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.event.ListEventsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.event.ListEventsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.event.EventClient.prototype.listEvents =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/event.Event/ListEvents',
      request,
      metadata || {},
      methodDescriptor_Event_ListEvents,
      callback);
};


/**
 * @param {!proto.event.ListEventsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.event.ListEventsResponse>}
 *     Promise that resolves to the response
 */
proto.event.EventPromiseClient.prototype.listEvents =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/event.Event/ListEvents',
      request,
      metadata || {},
      methodDescriptor_Event_ListEvents);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.event.NewEventRequest,
 *   !proto.event.NewEventResponse>}
 */
const methodDescriptor_Event_NewEvent = new grpc.web.MethodDescriptor(
  '/event.Event/NewEvent',
  grpc.web.MethodType.UNARY,
  proto.event.NewEventRequest,
  proto.event.NewEventResponse,
  /**
   * @param {!proto.event.NewEventRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.event.NewEventResponse.deserializeBinary
);


/**
 * @param {!proto.event.NewEventRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.event.NewEventResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.event.NewEventResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.event.EventClient.prototype.newEvent =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/event.Event/NewEvent',
      request,
      metadata || {},
      methodDescriptor_Event_NewEvent,
      callback);
};


/**
 * @param {!proto.event.NewEventRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.event.NewEventResponse>}
 *     Promise that resolves to the response
 */
proto.event.EventPromiseClient.prototype.newEvent =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/event.Event/NewEvent',
      request,
      metadata || {},
      methodDescriptor_Event_NewEvent);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.event.BetRequest,
 *   !proto.event.BetResponse>}
 */
const methodDescriptor_Event_Bet = new grpc.web.MethodDescriptor(
  '/event.Event/Bet',
  grpc.web.MethodType.UNARY,
  proto.event.BetRequest,
  proto.event.BetResponse,
  /**
   * @param {!proto.event.BetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.event.BetResponse.deserializeBinary
);


/**
 * @param {!proto.event.BetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.event.BetResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.event.BetResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.event.EventClient.prototype.bet =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/event.Event/Bet',
      request,
      metadata || {},
      methodDescriptor_Event_Bet,
      callback);
};


/**
 * @param {!proto.event.BetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.event.BetResponse>}
 *     Promise that resolves to the response
 */
proto.event.EventPromiseClient.prototype.bet =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/event.Event/Bet',
      request,
      metadata || {},
      methodDescriptor_Event_Bet);
};


module.exports = proto.event;

