services:
  auth: 
    image: go-image
    build:
      context:    ../docker
      dockerfile: go-image
    entrypoint: go run cmd/auth/main.go
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    container_name: auth
    ports:
     - 10000:10000
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext","localhost:10000", "describe"]
      interval: 5s
      retries: 10
    depends_on:
      - db

  auth-envoy:
    container_name: "auth-envoy"
    image: envoy/auth:latest
    ports:
      - "8000:8000"
  