services:
  shop: 
    image: go-image
    build:
      context:    ./docker
      dockerfile: go-image
    entrypoint: go run cmd/shop/main.go
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    container_name: shop
    ports:
     - 10001:10001
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext","localhost:10001", "describe"]
      interval: 5s
      retries: 10

  shop-envoy:
    container_name: "shop-envoy"
    image: envoy/shop:latest
    build:
      context:    envoy/shop
    ports:
      - "8001:8001"
  