services:
  user: 
    image: go-image
    build:
      context:    ../docker
      dockerfile: go-image
    entrypoint: go run cmd/user/main.go
    volumes:
      - "$PWD:$PWD:rw"
    working_dir: $PWD
    container_name: user
    ports:
     - 10002:10002
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext","localhost:10002", "describe"]
      interval: 5s
      retries: 10

  user-envoy:
    container_name: "user-envoy"
    image: envoy/user:latest
    ports:
      - "8002:8002"
  